---
title: "Biomarkers of ASD"
subtitle: "If you want a subtitle put it here"
author: "List names here"
date: last-modified
published-title: "Updated"
editor: visual
format: html
code-copy: true
execute:
  message: false
  warning: false
  echo: false
  cache: true
---

Use this as a template. Keep the headers and remove all other text. In all, your report can be quite short. When it is complete, render and then push changes to your team repository.

```{r}
# load any other packages and read data here
library(tidyverse)
```

## Abstract

Write a brief one-paragraph abstract that describes the contents of your write-up.

## Dataset

The data used in this study was obtained from voluntary participants who provided blood samples for analysis. A total of 154 male children were included in the study, with 76 boys diagnosed with ASD and 78 boys who were considered typically developed. The mean age in the groupw as 5.7 years old, and the most common ethnicity was White, though other ethnicities included were African American, Asian American, and Hispanic, among others. Demographic data about the participants was also collected surrounding any prevailing clinical conditions and medications being used. A total of 1,317 proteins were measured from the blood samples obtained, but 192 of those proteins were not considered suitable and were dropped from the analysis, leaving 1,125 proteins included in the study. The protein data was normalized by a log10 transform and a z transform, with any observations that exceeded a +3 or a -3 value after the z transformation being dropped as outliers.

## Summary of published analysis

Serum samples from boys with ASD and typically developing (TD) controls were analyzed using the SOMAScan™ platform, measuring 1,125 proteins after quality control. The methodology involved three primary statistical approaches to identify potential biomarkers: Random Forest (RF), t-tests, and correlation analysis with ADOS scores, a measure of ASD severity.

In the Random Forest method, feature importance scores were calculated to determine the most relevant proteins for distinguishing ASD from TD. The t-tests compared protein levels between the two groups to identify significant differences, while the correlation analysis sought proteins associated with ASD severity. The study combined the three methods by identifying the top 10 predictive proteins from each and cross-comparing them to find overlapping proteins consistently showing high importance. Five proteins were identified as a core set, and an additional 13 proteins were tested one by one to see if they increased the predictive value of the AUC using logistic regression. The classifier's performance was evaluated with repeated random splits of training and testing data.

The five core proteins are: mitogen-activated protein kinase 14 (MAPK14), immunoglobulin D (IgD), dermatopontin (DERM), ephrin type-B receptor 2 (EPHB2), and soluble urokinase-type plasminogen activator receptor (suPAR). Four additional proteins—receptor tyrosine kinase-like orphan receptor 1 (ROR1), platelet receptor Gl24 (GI24), eukaryotic translation initiation factor 4H (elF-4H), and arylsulfatase B (ARSB)—were selected to enhance predictive power. The final classifier, comprising these nine proteins, achieved an estimated accuracy with an area under the receiver operating characteristic curve (AUC) of 0.86, indicating strong discriminative ability for identifying ASD.

## Findings

Summarize your findings here. I've included some subheaders in a way that seems natural to me; you can structure this section however you like.

### Impact of preprocessing and outliers

Tasks 1-2

### Methodological variations

Task 3

### Improved classifier

Our new approach, was to use LASSO to select the important proteins in order to make a simpler yet comparable model instead of the Random Forest method. We fit binomial LASSO model with alpha = 1 and 10 cross-validation folds. We then used this model to choose the top 10 proteins with the highest absolute valued coefficients. Then, we took the common proteins between the multiple t-test and LASSO model for our final panel. We ended with a simpler model of 3 proteins that was comparable to the class-analysis: DERM, IgD, and FSTL1. This gave us an accuracy of 83.9%, Sensitivity = 87.5%, Specificity = 80%, Area under the ROC = 0.879.
